### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by eunha0ne** [eunha0ne/study-git-github#1]
프로젝트 시작을 위한 스켈레톤 작성
- main() 함수

**Comment by eunha0ne** [comment]
사칙연산을 담당하는 함수를 구분해서 작성하는 것이 좋을 것 같아요.
예를 들어서 ` add(int a, int b)`, `sub(int a, int b)` 등등

**Comment by eunha2nd** [comment]
@eunha0ne 좋습니다.
